Update patch set 25
Patch Set 25: Code-Review-1

There's something wrong with sending a Map-Notify on a cache hit:
2016-05-11 17:51:38,186 | ERROR | lisp-sb-6-1      | LispSouthboundHandler            | 259 - org.opendaylight.lispflowmapping.mappingservice.southbound - 1.4.0.SNAPSHOT | Error on channel: org.opendaylight.lispflowmapping.southbound.lisp.exception.LispMalformedPacketException: Couldn't deserialize Map-Register (len=88)
org.opendaylight.lispflowmapping.southbound.lisp.exception.LispMalformedPacketException: Couldn't deserialize Map-Register (len=88)
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.handleMapRegister(LispSouthboundHandler.java:223)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.handlePacket(LispSouthboundHandler.java:107)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.channelRead0(LispSouthboundHandler.java:344)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.channelRead0(LispSouthboundHandler.java:63)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)[139:io.netty.transport:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)[139:io.netty.transport:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[138:io.netty.common:4.0.36.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[138:io.netty.common:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]
Caused by: java.lang.UnsupportedOperationException
	at java.nio.ByteBuffer.array(ByteBuffer.java:994)[:1.8.0_74]
	at org.opendaylight.lispflowmapping.southbound.LispSouthboundPlugin.handleSerializedLispBuffer(LispSouthboundPlugin.java:161)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.sendMapNotifyMsg(LispSouthboundHandler.java:259)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	at org.opendaylight.lispflowmapping.southbound.lisp.LispSouthboundHandler.handleMapRegister(LispSouthboundHandler.java:192)[259:org.opendaylight.lispflowmapping.mappingservice.southbound:1.4.0.SNAPSHOT]
	... 15 more

Patch-set: 25
Label: Code-Review=-1