Update patch set 2
Patch Set 2: Code-Review-2

This breaks Map-Register performance tests. Relevant error in Karaf console:

2016-08-01 16:46:42,952 | ERROR | tp1052251085-585 | ContainerResponse                | 71 - com.sun.jersey.jersey-server - 1.17.0 | The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.IllegalStateException: New transaction PingPongTransaction{delegate=org.opendaylight.controller.cluster.databroker.DOMBrokerReadWriteTransaction@16c8dca1} raced with transacion PingPongTransaction{delegate=org.opendaylight.controller.cluster.
databroker.DOMBrokerReadWriteTransaction@7918668f}
        at org.opendaylight.controller.md.sal.dom.broker.impl.PingPongTransactionChain.slowAllocateTransaction(PingPongTransactionChain.java:136)
        at org.opendaylight.controller.md.sal.dom.broker.impl.PingPongTransactionChain.allocateTransaction(PingPongTransactionChain.java:148)
        at org.opendaylight.controller.md.sal.dom.broker.impl.PingPongTransactionChain.newReadWriteTransaction(PingPongTransactionChain.java:347)
        at org.opendaylight.controller.md.sal.dom.broker.impl.PingPongTransactionChain.newWriteOnlyTransaction(PingPongTransactionChain.java:378)
        at org.opendaylight.controller.md.sal.binding.impl.BindingDOMTransactionChainAdapter.newWriteOnlyTransaction(BindingDOMTransactionChainAdapter.java:75)
        at org.opendaylight.lispflowmapping.dsbackend.DataStoreBackEnd.writePutTransaction(DataStoreBackEnd.java:253)

Patch-set: 2